name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Сделать gradlew исполняемым
        run: chmod +x ./app/gradlew

      - name: Вывести файлы в директории app
        run: ls -la ./app  # Шаг отладки для проверки наличия Makefile

      - name: Сборка приложения
        run: make -C app build  # Убедитесь, что вы собираете из правильной директории

      - name: Запуск Jacoco Test Report
        run: cd app && ./gradlew jacocoTestReport  # Запустить Jacoco отчет

      - name: Публикация покрытия кода
        uses: paambaati/codeclimate-action@v9.0.0
        env:
           CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
           JACOCO_SOURCE_PATH: app/src/main/java
        with:
           coverageCommand: ./app/gradlew jacocoTestReport
           coverageLocations: ${{ github.workspace }}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco

