name: ci

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and setup java
        uses: actions/checkout@v4
        uses: actions/setup-java@v3
	with:
	   java-version: '21'
      - name: build
        run: make -C app build

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
           CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
           JACOCO_SOURCE_PATH: app/src/main/java
        with:
           coverageCommand: ./gradlew jacocoTestReport
           coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
