name: CI Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: action/checkout@v4

        - name: Set up node
          uses: action/setup-node@v4
          with:
            node-version: '23.x'
            cache: 'npm'

        - name: Start build
          run: make build
